title : Cal-ICOR Documentation
author: Cal-ICOR gang
logo: 'assets/logo-trans.png'

# Short description about the book
description: >-
  Documentation for all things ICOR

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/cal-icor/docs.git
  path_to_book                : "book"

# LaTeX settings
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
